# Generated by Django 3.2.8 on 2021-11-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211102_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_category',
        ),
        migrations.AddField(
            model_name='roles',
            name='work_category',
            field=models.ManyToManyField(to='users.Category'),
        ),
    ]
