# Generated by Django 3.2.8 on 2021-11-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211102_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='work_category',
            field=models.ManyToManyField(default=None, null=True, to='users.Category'),
        ),
    ]
