# Generated by Django 3.2.8 on 2021-11-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_roles_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='work_category',
            field=models.ManyToManyField(blank=True, default=None, to='users.Category'),
        ),
    ]
