# Generated by Django 3.2.8 on 2021-11-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_roles_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.shops'),
        ),
    ]
