# Generated by Django 3.2.8 on 2021-11-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='autor_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
