# Generated by Django 3.2.8 on 2021-11-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='autor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='comments',
            name='object_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
