# Generated by Django 3.2.8 on 2021-11-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_autor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='autor_id',
            field=models.CharField(max_length=50),
        ),
    ]
