# Generated by Django 3.2.8 on 2021-11-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comments_autor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='autor_id',
            new_name='autor',
        ),
    ]
