# Generated by Django 3.2.8 on 2021-11-24 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zayavki', '0008_auto_20211123_2224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=250)),
                ('recipient', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
                ('zayavka', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='zayavki.zayavka')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
