# Generated by Django 3.2.8 on 2021-11-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_alter_user_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('clarification', models.TextField()),
                ('foto1', models.ImageField(blank=True, upload_to='zayavki/foto')),
                ('foto2', models.ImageField(blank=True, upload_to='zayavki/foto')),
                ('status1', models.BooleanField(default=False)),
                ('status2', models.BooleanField(default=False)),
                ('status3', models.BooleanField(default=False)),
                ('status4', models.BooleanField(default=False)),
                ('status5', models.BooleanField(default=False)),
                ('status6', models.BooleanField(default=False)),
                ('clarification_of_manager', models.CharField(blank=True, max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.category')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=10)),
                ('status1', models.BooleanField(default=False)),
                ('status2', models.BooleanField(default=False)),
                ('status3', models.BooleanField(default=False)),
                ('status4', models.BooleanField(default=False)),
                ('status5', models.BooleanField(default=False)),
                ('status6', models.BooleanField(default=False)),
                ('is_default_for_users', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фильтр заявок',
                'verbose_name_plural': 'Фильтры заявок',
            },
        ),
    ]
