# Generated by Django 3.1.7 on 2021-10-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('clarification', models.TextField()),
                ('foto1', models.ImageField(blank=True, upload_to='zayavki/foto')),
                ('foto2', models.ImageField(blank=True, upload_to='zayavki/foto')),
                ('status1', models.BooleanField()),
                ('status2', models.BooleanField()),
                ('status3', models.BooleanField()),
                ('status4', models.BooleanField()),
                ('status5', models.BooleanField()),
                ('status6', models.BooleanField()),
                ('clarification_of_manager', models.CharField(blank=True, max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zayavki.category')),
            ],
        ),
    ]
