# Generated by Django 3.2.8 on 2021-10-31 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zayavki', '0002_auto_20211028_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='shop',
        ),
        migrations.AddField(
            model_name='zayavka',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
    ]
