# Generated by Django 3.2.8 on 2021-11-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0002_delete_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
    ]
