# Generated by Django 3.2.8 on 2021-11-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0003_filters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filters',
        ),
    ]
