# Generated by Django 3.2.8 on 2021-10-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0003_auto_20211031_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zayavka',
            old_name='user',
            new_name='who',
        ),
    ]
