# Generated by Django 3.2.8 on 2021-11-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0005_auto_20211123_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersofzayavok',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filtersofzayavok',
            name='status1',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='filtersofzayavok',
            name='status2',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='filtersofzayavok',
            name='status3',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='filtersofzayavok',
            name='status4',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='filtersofzayavok',
            name='status5',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='filtersofzayavok',
            name='status6',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
