# Generated by Django 3.2.8 on 2021-11-23 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211123_1030'),
        ('zayavki', '0006_auto_20211123_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtersofzayavok',
            name='for_roles',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.roles'),
        ),
    ]
