# Generated by Django 3.2.8 on 2021-10-31 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zayavki', '0006_alter_zayavka_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='who',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
