# Generated by Django 3.2.8 on 2021-10-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0007_alter_zayavka_who'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zayavka',
            old_name='who',
            new_name='user',
        ),
    ]
