# Generated by Django 3.2.8 on 2021-11-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211123_1030'),
        ('zayavki', '0007_filtersofzayavok_for_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtersofzayavok',
            name='for_roles',
        ),
        migrations.AddField(
            model_name='filtersofzayavok',
            name='for_roles',
            field=models.ManyToManyField(default=None, null=True, to='users.Roles'),
        ),
    ]
