# Generated by Django 3.2.8 on 2021-11-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211123_1030'),
        ('zayavki', '0008_auto_20211123_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersofzayavok',
            name='for_roles',
            field=models.ManyToManyField(default=None, to='users.Roles'),
        ),
    ]
