# Generated by Django 3.2.8 on 2021-11-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_shop'),
        ('zayavki', '0009_auto_20211102_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='shop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.shops'),
        ),
    ]
