# Generated by Django 3.2.8 on 2021-12-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211123_1030'),
        ('zayavki', '0009_alter_filtersofzayavok_for_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveSmallIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(default='', max_length=50)),
                ('body', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AlterField(
            model_name='filtersofzayavok',
            name='for_roles',
            field=models.ManyToManyField(to='users.Roles'),
        ),
    ]
