# Generated by Django 3.2.8 on 2021-11-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0010_zayavka_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='shop',
        ),
    ]
