# Generated by Django 3.2.8 on 2021-12-02 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zayavki', '0010_auto_20211201_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=250)),
                ('recipient', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('zayavka', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='zayavki.zayavka')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
