# Generated by Django 3.2.8 on 2021-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0012_auto_20211104_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='status1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status3',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status4',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status5',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status6',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
