# Generated by Django 3.2.8 on 2021-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0013_auto_20211104_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='status1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status6',
            field=models.BooleanField(default=False),
        ),
    ]
