# Generated by Django 3.2.8 on 2021-11-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0014_auto_20211105_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=10)),
                ('status1', models.BooleanField(default=False)),
                ('status2', models.BooleanField(default=False)),
                ('status3', models.BooleanField(default=False)),
                ('status4', models.BooleanField(default=False)),
                ('status5', models.BooleanField(default=False)),
                ('status6', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Фильтр заявок',
                'verbose_name_plural': 'Фильтры заявок',
            },
        ),
        migrations.AddField(
            model_name='zayavka',
            name='filter_default',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='zayavki.filters'),
        ),
    ]
