# Generated by Django 3.2.8 on 2021-11-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0015_auto_20211122_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='filter_default',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='zayavki.filters'),
        ),
    ]
