# Generated by Django 3.2.8 on 2021-11-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0016_alter_zayavka_filter_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='filter_default',
        ),
    ]
